/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module maze_map_rom_16 (
    input [3:0] address,
    input clk,
    input rst,
    output reg [7:0] map
  );
  
  
  
  localparam ROW_1 = 8'h80;
  
  localparam ROW_2 = 8'hf0;
  
  localparam ROW_3 = 8'h17;
  
  localparam ROW_4 = 8'hfc;
  
  localparam ROW_5 = 8'h10;
  
  localparam ROW_6 = 8'hfc;
  
  localparam ROW_7 = 8'h77;
  
  localparam ROW_8 = 8'h45;
  
  always @* begin
    if (address == 4'h0) begin
      map = 8'h80;
    end else begin
      if (address == 4'h1) begin
        map = 8'hf0;
      end else begin
        if (address == 4'h2) begin
          map = 8'h17;
        end else begin
          if (address == 4'h3) begin
            map = 8'hfc;
          end else begin
            if (address == 4'h4) begin
              map = 8'h10;
            end else begin
              if (address == 4'h5) begin
                map = 8'hfc;
              end else begin
                if (address == 4'h6) begin
                  map = 8'h77;
                end else begin
                  if (address == 4'h7) begin
                    map = 8'h45;
                  end else begin
                    map = 1'h0;
                  end
                end
              end
            end
          end
        end
      end
    end
  end
endmodule
